### ISSUE TITLE
display message when game is over

### ISSUE THREAD

**Issue by Annrison** [marvinkreis/whisker-web#10]
hello, when the game is over, the panda should display message for two seconds, for testing I set panda in sb3 file to display the message for only one second.

I use `const timeElapsed = await t.runUntil(() => panda.sayText, 40000);` to wait until the panda to display message, but when I check the panda's sprite, the `panda.sayText` is "". Is there a way to fix this ?

Also I would like to ask that , must the function have to get the clones of donut to play the game ? Or it could also wait until the time variable is 0 or something like that ?

```javascript
const testTimerGameOverMessage = async function (t) {
    t.seedScratch('seed');

    // let {bowl, apple} = getSpritesAndVariables(t, ['bowl', 'apple']);
    let panda = t.getSprite('panda');
    let p_donut = t.getSprite('pink_donut');

    /* Play the game, so the timer can tick long enough. */
    t.addCallback(() => {
        p_donut = getNewestClone(p_donut);
        followSprite(t, panda.x, p_donut.x);
    });

    const timeElapsed = await t.runUntil(() => panda.sayText, 40000);
    console.log("testTimerGameOverMessage panda",panda)
    t.assert.ok(panda.sayText, 'panda must display a message when the time is up.');
    t.assert.matches(panda.sayText.toLowerCase(), gameOverRegex, 'panda must display \'game over!\' when the time is up.');
    t.assert.greaterOrEqual(timeElapsed, 20000, 'Game over message must not appear before 20 seconds.');

    await t.runForTime(1000);
    t.assert.ok(panda.sayText, 'panda\'s game over message must last for two seconds.');

    await t.runUntil(() => !panda.sayText, 1000);
    t.assert.ok(!panda.sayText, 'panda\'s game over message must disappear after two seconds');

    t.end();
};


module.exports = [
{ // 28
        test: testTimerGameOverMessage,
        name: 'Timer Game Over Message Test',
        description: 'Tests if the game displays a game over message after the time limit is reached.',
        categories: ['timer', 'time', 'input', 'slow']
    }
]
```

file link:
.sb3 (with error, only display message for one second)
https://u.pcloud.link/publink/show?code=XZbUbJXZ2vieE38aD75xlFQ86HuQyyLDG8u7

.js file for testing
https://u.pcloud.link/publink/show?code=XZqapJXZiSn2zS6uCPRoMy4Fqh05yFMeLFIX

**Comment by marvinkreis** [comment]
I don't have the problem with `panda.sayText == ""`. When I print the `sayText` (with the code below) it says "game over".
```javascript
    // ...
    const timeElapsed = await t.runUntil(() => panda.sayText, 40000);
    console.log(panda.sayText);
    console.log("testTimerGameOverMessage panda",panda)
    // ...
```
When I run `testTimerGameOverMessage`, I get this outcome:
```yaml
TAP version 13
1..1
not ok 1 - Timer Game Over Message Test
  ---
  severity: fail
  error:
    name: AssertionError
    actual: false
    expected: true
    operator: ok
    message: panda's game over message must last for two seconds.
    generatedMessage: false
  ...
```


---

For your project, I believe it's enough to let the timer run out without catching the donuts. The original tests were for a project, in which the player had to catch apples with a bowl. And if an apple touched the ground the game would stop before the timer runs out. This is why this test tried to catch the apples, otherwise the timer could not be tested.

**Comment by Annrison** [comment]
Thank you so much, I got the point and would modify the timer function without catching the donuts, by the way, I test the file again and got the message this time, maybe I mistook the wrong file.
